// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: network.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Via           string                 `protobuf:"bytes,4,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCreateRequest) Reset() {
	*x = NetworkCreateRequest{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCreateRequest) ProtoMessage() {}

func (x *NetworkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCreateRequest.ProtoReflect.Descriptor instead.
func (*NetworkCreateRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkCreateRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkCreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkCreateRequest) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type NetworkListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkListRequest) Reset() {
	*x = NetworkListRequest{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkListRequest) ProtoMessage() {}

func (x *NetworkListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkListRequest.ProtoReflect.Descriptor instead.
func (*NetworkListRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

type NetworkDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDeleteRequest) Reset() {
	*x = NetworkDeleteRequest{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDeleteRequest) ProtoMessage() {}

func (x *NetworkDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDeleteRequest.ProtoReflect.Descriptor instead.
func (*NetworkDeleteRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NetworkGetAllTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGetAllTypesRequest) Reset() {
	*x = NetworkGetAllTypesRequest{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGetAllTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGetAllTypesRequest) ProtoMessage() {}

func (x *NetworkGetAllTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGetAllTypesRequest.ProtoReflect.Descriptor instead.
func (*NetworkGetAllTypesRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

type NetworkAssociateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAssociateRequest) Reset() {
	*x = NetworkAssociateRequest{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAssociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAssociateRequest) ProtoMessage() {}

func (x *NetworkAssociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAssociateRequest.ProtoReflect.Descriptor instead.
func (*NetworkAssociateRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkAssociateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkAssociateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NetworkDissociateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDissociateRequest) Reset() {
	*x = NetworkDissociateRequest{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDissociateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDissociateRequest) ProtoMessage() {}

func (x *NetworkDissociateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDissociateRequest.ProtoReflect.Descriptor instead.
func (*NetworkDissociateRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkDissociateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkDissociateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NetworkGetAssociatedUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGetAssociatedUsersRequest) Reset() {
	*x = NetworkGetAssociatedUsersRequest{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGetAssociatedUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGetAssociatedUsersRequest) ProtoMessage() {}

func (x *NetworkGetAssociatedUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGetAssociatedUsersRequest.ProtoReflect.Descriptor instead.
func (*NetworkGetAssociatedUsersRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkGetAssociatedUsersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Network struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cidr                string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AssociatedUsernames []string               `protobuf:"bytes,5,rep,name=associated_usernames,json=associatedUsernames,proto3" json:"associated_usernames,omitempty"`
	Via                 string                 `protobuf:"bytes,6,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Network) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Network) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Network) GetAssociatedUsernames() []string {
	if x != nil {
		return x.AssociatedUsernames
	}
	return nil
}

func (x *Network) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

type NetworkType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkType) Reset() {
	*x = NetworkType{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkType) ProtoMessage() {}

func (x *NetworkType) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkType.ProtoReflect.Descriptor instead.
func (*NetworkType) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetworkType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type NetworkCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *Network               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCreateResponse) Reset() {
	*x = NetworkCreateResponse{}
	mi := &file_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCreateResponse) ProtoMessage() {}

func (x *NetworkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCreateResponse.ProtoReflect.Descriptor instead.
func (*NetworkCreateResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkCreateResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type NetworkListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*Network             `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkListResponse) Reset() {
	*x = NetworkListResponse{}
	mi := &file_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkListResponse) ProtoMessage() {}

func (x *NetworkListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkListResponse.ProtoReflect.Descriptor instead.
func (*NetworkListResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkListResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

type NetworkDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *Network               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDeleteResponse) Reset() {
	*x = NetworkDeleteResponse{}
	mi := &file_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDeleteResponse) ProtoMessage() {}

func (x *NetworkDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDeleteResponse.ProtoReflect.Descriptor instead.
func (*NetworkDeleteResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkDeleteResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type NetworkGetAllTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*NetworkType         `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGetAllTypesResponse) Reset() {
	*x = NetworkGetAllTypesResponse{}
	mi := &file_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGetAllTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGetAllTypesResponse) ProtoMessage() {}

func (x *NetworkGetAllTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGetAllTypesResponse.ProtoReflect.Descriptor instead.
func (*NetworkGetAllTypesResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkGetAllTypesResponse) GetTypes() []*NetworkType {
	if x != nil {
		return x.Types
	}
	return nil
}

type NetworkAssociateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAssociateResponse) Reset() {
	*x = NetworkAssociateResponse{}
	mi := &file_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAssociateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAssociateResponse) ProtoMessage() {}

func (x *NetworkAssociateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAssociateResponse.ProtoReflect.Descriptor instead.
func (*NetworkAssociateResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{13}
}

type NetworkDissociateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkDissociateResponse) Reset() {
	*x = NetworkDissociateResponse{}
	mi := &file_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDissociateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDissociateResponse) ProtoMessage() {}

func (x *NetworkDissociateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDissociateResponse.ProtoReflect.Descriptor instead.
func (*NetworkDissociateResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{14}
}

type NetworkGetAssociatedUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usernames     []string               `protobuf:"bytes,1,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGetAssociatedUsersResponse) Reset() {
	*x = NetworkGetAssociatedUsersResponse{}
	mi := &file_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGetAssociatedUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGetAssociatedUsersResponse) ProtoMessage() {}

func (x *NetworkGetAssociatedUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGetAssociatedUsersResponse.ProtoReflect.Descriptor instead.
func (*NetworkGetAssociatedUsersResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkGetAssociatedUsersResponse) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"d\n" +
	"\x14NetworkCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03via\x18\x04 \x01(\tR\x03via\"\x14\n" +
	"\x12NetworkListRequest\"*\n" +
	"\x14NetworkDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x19NetworkGetAllTypesRequest\"I\n" +
	"\x17NetworkAssociateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"J\n" +
	"\x18NetworkDissociateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"6\n" +
	" NetworkGetAssociatedUsersRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa9\x01\n" +
	"\aNetwork\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x121\n" +
	"\x14associated_usernames\x18\x05 \x03(\tR\x13associatedUsernames\x12\x10\n" +
	"\x03via\x18\x06 \x01(\tR\x03via\"C\n" +
	"\vNetworkType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\">\n" +
	"\x15NetworkCreateResponse\x12%\n" +
	"\anetwork\x18\x01 \x01(\v2\v.pb.NetworkR\anetwork\">\n" +
	"\x13NetworkListResponse\x12'\n" +
	"\bnetworks\x18\x01 \x03(\v2\v.pb.NetworkR\bnetworks\">\n" +
	"\x15NetworkDeleteResponse\x12%\n" +
	"\anetwork\x18\x01 \x01(\v2\v.pb.NetworkR\anetwork\"C\n" +
	"\x1aNetworkGetAllTypesResponse\x12%\n" +
	"\x05types\x18\x01 \x03(\v2\x0f.pb.NetworkTypeR\x05types\"\x1a\n" +
	"\x18NetworkAssociateResponse\"\x1b\n" +
	"\x19NetworkDissociateResponse\"A\n" +
	"!NetworkGetAssociatedUsersResponse\x12\x1c\n" +
	"\tusernames\x18\x01 \x03(\tR\tusernames2\x8e\x06\n" +
	"\x0eNetworkService\x12`\n" +
	"\x06Create\x12\x18.pb.NetworkCreateRequest\x1a\x19.pb.NetworkCreateResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/network/create\x12U\n" +
	"\x04List\x12\x16.pb.NetworkListRequest\x1a\x17.pb.NetworkListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/network/list\x12`\n" +
	"\x06Delete\x12\x18.pb.NetworkDeleteRequest\x1a\x19.pb.NetworkDeleteResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/network/delete\x12q\n" +
	"\vGetAllTypes\x12\x1d.pb.NetworkGetAllTypesRequest\x1a\x1e.pb.NetworkGetAllTypesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/network/getalltypes\x12\x8d\x01\n" +
	"\x12GetAssociatedUsers\x12$.pb.NetworkGetAssociatedUsersRequest\x1a%.pb.NetworkGetAssociatedUsersResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/v1/network/getassociatedusers\x12l\n" +
	"\tAssociate\x12\x1b.pb.NetworkAssociateRequest\x1a\x1c.pb.NetworkAssociateResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/network/associate\x12p\n" +
	"\n" +
	"Dissociate\x12\x1c.pb.NetworkDissociateRequest\x1a\x1d.pb.NetworkDissociateResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/network/dissociateB\x1cZ\x1agithub.com/GoldenRUS/ovpm/api/pbb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_network_proto_goTypes = []any{
	(*NetworkCreateRequest)(nil),              // 0: pb.NetworkCreateRequest
	(*NetworkListRequest)(nil),                // 1: pb.NetworkListRequest
	(*NetworkDeleteRequest)(nil),              // 2: pb.NetworkDeleteRequest
	(*NetworkGetAllTypesRequest)(nil),         // 3: pb.NetworkGetAllTypesRequest
	(*NetworkAssociateRequest)(nil),           // 4: pb.NetworkAssociateRequest
	(*NetworkDissociateRequest)(nil),          // 5: pb.NetworkDissociateRequest
	(*NetworkGetAssociatedUsersRequest)(nil),  // 6: pb.NetworkGetAssociatedUsersRequest
	(*Network)(nil),                           // 7: pb.Network
	(*NetworkType)(nil),                       // 8: pb.NetworkType
	(*NetworkCreateResponse)(nil),             // 9: pb.NetworkCreateResponse
	(*NetworkListResponse)(nil),               // 10: pb.NetworkListResponse
	(*NetworkDeleteResponse)(nil),             // 11: pb.NetworkDeleteResponse
	(*NetworkGetAllTypesResponse)(nil),        // 12: pb.NetworkGetAllTypesResponse
	(*NetworkAssociateResponse)(nil),          // 13: pb.NetworkAssociateResponse
	(*NetworkDissociateResponse)(nil),         // 14: pb.NetworkDissociateResponse
	(*NetworkGetAssociatedUsersResponse)(nil), // 15: pb.NetworkGetAssociatedUsersResponse
}
var file_network_proto_depIdxs = []int32{
	7,  // 0: pb.NetworkCreateResponse.network:type_name -> pb.Network
	7,  // 1: pb.NetworkListResponse.networks:type_name -> pb.Network
	7,  // 2: pb.NetworkDeleteResponse.network:type_name -> pb.Network
	8,  // 3: pb.NetworkGetAllTypesResponse.types:type_name -> pb.NetworkType
	0,  // 4: pb.NetworkService.Create:input_type -> pb.NetworkCreateRequest
	1,  // 5: pb.NetworkService.List:input_type -> pb.NetworkListRequest
	2,  // 6: pb.NetworkService.Delete:input_type -> pb.NetworkDeleteRequest
	3,  // 7: pb.NetworkService.GetAllTypes:input_type -> pb.NetworkGetAllTypesRequest
	6,  // 8: pb.NetworkService.GetAssociatedUsers:input_type -> pb.NetworkGetAssociatedUsersRequest
	4,  // 9: pb.NetworkService.Associate:input_type -> pb.NetworkAssociateRequest
	5,  // 10: pb.NetworkService.Dissociate:input_type -> pb.NetworkDissociateRequest
	9,  // 11: pb.NetworkService.Create:output_type -> pb.NetworkCreateResponse
	10, // 12: pb.NetworkService.List:output_type -> pb.NetworkListResponse
	11, // 13: pb.NetworkService.Delete:output_type -> pb.NetworkDeleteResponse
	12, // 14: pb.NetworkService.GetAllTypes:output_type -> pb.NetworkGetAllTypesResponse
	15, // 15: pb.NetworkService.GetAssociatedUsers:output_type -> pb.NetworkGetAssociatedUsersResponse
	13, // 16: pb.NetworkService.Associate:output_type -> pb.NetworkAssociateResponse
	14, // 17: pb.NetworkService.Dissociate:output_type -> pb.NetworkDissociateResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
