// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: statistic.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatisticListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticListRequest) Reset() {
	*x = StatisticListRequest{}
	mi := &file_statistic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticListRequest) ProtoMessage() {}

func (x *StatisticListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticListRequest.ProtoReflect.Descriptor instead.
func (*StatisticListRequest) Descriptor() ([]byte, []int) {
	return file_statistic_proto_rawDescGZIP(), []int{0}
}

type StatisticWithFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      string                 `protobuf:"bytes,1,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	DateTo        string                 `protobuf:"bytes,2,opt,name=dateTo,proto3" json:"dateTo,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticWithFilterRequest) Reset() {
	*x = StatisticWithFilterRequest{}
	mi := &file_statistic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticWithFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticWithFilterRequest) ProtoMessage() {}

func (x *StatisticWithFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticWithFilterRequest.ProtoReflect.Descriptor instead.
func (*StatisticWithFilterRequest) Descriptor() ([]byte, []int) {
	return file_statistic_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticWithFilterRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *StatisticWithFilterRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *StatisticWithFilterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type StatisticResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Statistic     []*StatisticResponse_Statistic `protobuf:"bytes,1,rep,name=statistic,proto3" json:"statistic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticResponse) Reset() {
	*x = StatisticResponse{}
	mi := &file_statistic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticResponse) ProtoMessage() {}

func (x *StatisticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticResponse.ProtoReflect.Descriptor instead.
func (*StatisticResponse) Descriptor() ([]byte, []int) {
	return file_statistic_proto_rawDescGZIP(), []int{2}
}

func (x *StatisticResponse) GetStatistic() []*StatisticResponse_Statistic {
	if x != nil {
		return x.Statistic
	}
	return nil
}

type StatisticResponse_Statistic struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Username              string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ConnectionCount       int64                  `protobuf:"varint,2,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	TotalBytesReceived    int64                  `protobuf:"varint,3,opt,name=total_bytes_received,json=totalBytesReceived,proto3" json:"total_bytes_received,omitempty"`
	TotalBytesSent        int64                  `protobuf:"varint,4,opt,name=total_bytes_sent,json=totalBytesSent,proto3" json:"total_bytes_sent,omitempty"`
	TotalBytes            int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvgConnectionDuration int64                  `protobuf:"varint,6,opt,name=avg_connection_duration,json=avgConnectionDuration,proto3" json:"avg_connection_duration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatisticResponse_Statistic) Reset() {
	*x = StatisticResponse_Statistic{}
	mi := &file_statistic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticResponse_Statistic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticResponse_Statistic) ProtoMessage() {}

func (x *StatisticResponse_Statistic) ProtoReflect() protoreflect.Message {
	mi := &file_statistic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticResponse_Statistic.ProtoReflect.Descriptor instead.
func (*StatisticResponse_Statistic) Descriptor() ([]byte, []int) {
	return file_statistic_proto_rawDescGZIP(), []int{2, 0}
}

func (x *StatisticResponse_Statistic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StatisticResponse_Statistic) GetConnectionCount() int64 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *StatisticResponse_Statistic) GetTotalBytesReceived() int64 {
	if x != nil {
		return x.TotalBytesReceived
	}
	return 0
}

func (x *StatisticResponse_Statistic) GetTotalBytesSent() int64 {
	if x != nil {
		return x.TotalBytesSent
	}
	return 0
}

func (x *StatisticResponse_Statistic) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StatisticResponse_Statistic) GetAvgConnectionDuration() int64 {
	if x != nil {
		return x.AvgConnectionDuration
	}
	return 0
}

var File_statistic_proto protoreflect.FileDescriptor

const file_statistic_proto_rawDesc = "" +
	"\n" +
	"\x0fstatistic.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x16\n" +
	"\x14StatisticListRequest\"l\n" +
	"\x1aStatisticWithFilterRequest\x12\x1a\n" +
	"\bdateFrom\x18\x01 \x01(\tR\bdateFrom\x12\x16\n" +
	"\x06dateTo\x18\x02 \x01(\tR\x06dateTo\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\xdc\x02\n" +
	"\x11StatisticResponse\x12=\n" +
	"\tstatistic\x18\x01 \x03(\v2\x1f.pb.StatisticResponse.StatisticR\tstatistic\x1a\x87\x02\n" +
	"\tStatistic\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12)\n" +
	"\x10connection_count\x18\x02 \x01(\x03R\x0fconnectionCount\x120\n" +
	"\x14total_bytes_received\x18\x03 \x01(\x03R\x12totalBytesReceived\x12(\n" +
	"\x10total_bytes_sent\x18\x04 \x01(\x03R\x0etotalBytesSent\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x126\n" +
	"\x17avg_connection_duration\x18\x06 \x01(\x03R\x15avgConnectionDuration2\xd4\x01\n" +
	"\x10StatisticService\x12W\n" +
	"\x04List\x12\x18.pb.StatisticListRequest\x1a\x15.pb.StatisticResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/statistic/list\x12g\n" +
	"\vWFilterList\x12\x1e.pb.StatisticWithFilterRequest\x1a\x15.pb.StatisticResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/statistic/listB\"Z github.com/GoldenRUS/ovpm/api/pbb\x06proto3"

var (
	file_statistic_proto_rawDescOnce sync.Once
	file_statistic_proto_rawDescData []byte
)

func file_statistic_proto_rawDescGZIP() []byte {
	file_statistic_proto_rawDescOnce.Do(func() {
		file_statistic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistic_proto_rawDesc), len(file_statistic_proto_rawDesc)))
	})
	return file_statistic_proto_rawDescData
}

var file_statistic_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_statistic_proto_goTypes = []any{
	(*StatisticListRequest)(nil),        // 0: pb.StatisticListRequest
	(*StatisticWithFilterRequest)(nil),  // 1: pb.StatisticWithFilterRequest
	(*StatisticResponse)(nil),           // 2: pb.StatisticResponse
	(*StatisticResponse_Statistic)(nil), // 3: pb.StatisticResponse.Statistic
}
var file_statistic_proto_depIdxs = []int32{
	3, // 0: pb.StatisticResponse.statistic:type_name -> pb.StatisticResponse.Statistic
	0, // 1: pb.StatisticService.List:input_type -> pb.StatisticListRequest
	1, // 2: pb.StatisticService.WFilterList:input_type -> pb.StatisticWithFilterRequest
	2, // 3: pb.StatisticService.List:output_type -> pb.StatisticResponse
	2, // 4: pb.StatisticService.WFilterList:output_type -> pb.StatisticResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_statistic_proto_init() }
func file_statistic_proto_init() {
	if File_statistic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistic_proto_rawDesc), len(file_statistic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistic_proto_goTypes,
		DependencyIndexes: file_statistic_proto_depIdxs,
		MessageInfos:      file_statistic_proto_msgTypes,
	}.Build()
	File_statistic_proto = out.File
	file_statistic_proto_goTypes = nil
	file_statistic_proto_depIdxs = nil
}
