// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserUpdateRequest_GWPref int32

const (
	UserUpdateRequest_NOPREF UserUpdateRequest_GWPref = 0
	UserUpdateRequest_NOGW   UserUpdateRequest_GWPref = 1
	UserUpdateRequest_GW     UserUpdateRequest_GWPref = 2
)

// Enum value maps for UserUpdateRequest_GWPref.
var (
	UserUpdateRequest_GWPref_name = map[int32]string{
		0: "NOPREF",
		1: "NOGW",
		2: "GW",
	}
	UserUpdateRequest_GWPref_value = map[string]int32{
		"NOPREF": 0,
		"NOGW":   1,
		"GW":     2,
	}
)

func (x UserUpdateRequest_GWPref) Enum() *UserUpdateRequest_GWPref {
	p := new(UserUpdateRequest_GWPref)
	*p = x
	return p
}

func (x UserUpdateRequest_GWPref) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserUpdateRequest_GWPref) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (UserUpdateRequest_GWPref) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x UserUpdateRequest_GWPref) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserUpdateRequest_GWPref.Descriptor instead.
func (UserUpdateRequest_GWPref) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2, 0}
}

type UserUpdateRequest_StaticPref int32

const (
	UserUpdateRequest_NOPREFSTATIC UserUpdateRequest_StaticPref = 0
	UserUpdateRequest_NOSTATIC     UserUpdateRequest_StaticPref = 1
	UserUpdateRequest_STATIC       UserUpdateRequest_StaticPref = 2
)

// Enum value maps for UserUpdateRequest_StaticPref.
var (
	UserUpdateRequest_StaticPref_name = map[int32]string{
		0: "NOPREFSTATIC",
		1: "NOSTATIC",
		2: "STATIC",
	}
	UserUpdateRequest_StaticPref_value = map[string]int32{
		"NOPREFSTATIC": 0,
		"NOSTATIC":     1,
		"STATIC":       2,
	}
)

func (x UserUpdateRequest_StaticPref) Enum() *UserUpdateRequest_StaticPref {
	p := new(UserUpdateRequest_StaticPref)
	*p = x
	return p
}

func (x UserUpdateRequest_StaticPref) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserUpdateRequest_StaticPref) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (UserUpdateRequest_StaticPref) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x UserUpdateRequest_StaticPref) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserUpdateRequest_StaticPref.Descriptor instead.
func (UserUpdateRequest_StaticPref) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2, 1}
}

type UserUpdateRequest_AdminPref int32

const (
	UserUpdateRequest_NOPREFADMIN UserUpdateRequest_AdminPref = 0
	UserUpdateRequest_NOADMIN     UserUpdateRequest_AdminPref = 1
	UserUpdateRequest_ADMIN       UserUpdateRequest_AdminPref = 2
)

// Enum value maps for UserUpdateRequest_AdminPref.
var (
	UserUpdateRequest_AdminPref_name = map[int32]string{
		0: "NOPREFADMIN",
		1: "NOADMIN",
		2: "ADMIN",
	}
	UserUpdateRequest_AdminPref_value = map[string]int32{
		"NOPREFADMIN": 0,
		"NOADMIN":     1,
		"ADMIN":       2,
	}
)

func (x UserUpdateRequest_AdminPref) Enum() *UserUpdateRequest_AdminPref {
	p := new(UserUpdateRequest_AdminPref)
	*p = x
	return p
}

func (x UserUpdateRequest_AdminPref) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserUpdateRequest_AdminPref) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[2].Descriptor()
}

func (UserUpdateRequest_AdminPref) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[2]
}

func (x UserUpdateRequest_AdminPref) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserUpdateRequest_AdminPref.Descriptor instead.
func (UserUpdateRequest_AdminPref) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2, 2}
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type UserCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NoGw          bool                   `protobuf:"varint,3,opt,name=no_gw,json=noGw,proto3" json:"no_gw,omitempty"`
	HostId        uint32                 `protobuf:"varint,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateRequest) GetNoGw() bool {
	if x != nil {
		return x.NoGw
	}
	return false
}

func (x *UserCreateRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *UserCreateRequest) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserUpdateRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Username      string                       `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                       `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Gwpref        UserUpdateRequest_GWPref     `protobuf:"varint,3,opt,name=gwpref,proto3,enum=pb.UserUpdateRequest_GWPref" json:"gwpref,omitempty"`
	HostId        uint32                       `protobuf:"varint,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	StaticPref    UserUpdateRequest_StaticPref `protobuf:"varint,5,opt,name=static_pref,json=staticPref,proto3,enum=pb.UserUpdateRequest_StaticPref" json:"static_pref,omitempty"`
	AdminPref     UserUpdateRequest_AdminPref  `protobuf:"varint,6,opt,name=admin_pref,json=adminPref,proto3,enum=pb.UserUpdateRequest_AdminPref" json:"admin_pref,omitempty"`
	Description   string                       `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserUpdateRequest) GetGwpref() UserUpdateRequest_GWPref {
	if x != nil {
		return x.Gwpref
	}
	return UserUpdateRequest_NOPREF
}

func (x *UserUpdateRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *UserUpdateRequest) GetStaticPref() UserUpdateRequest_StaticPref {
	if x != nil {
		return x.StaticPref
	}
	return UserUpdateRequest_NOPREFSTATIC
}

func (x *UserUpdateRequest) GetAdminPref() UserUpdateRequest_AdminPref {
	if x != nil {
		return x.AdminPref
	}
	return UserUpdateRequest_NOPREFADMIN
}

func (x *UserUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRenewRequest) Reset() {
	*x = UserRenewRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRenewRequest) ProtoMessage() {}

func (x *UserRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRenewRequest.ProtoReflect.Descriptor instead.
func (*UserRenewRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserRenewRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserGenConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGenConfigRequest) Reset() {
	*x = UserGenConfigRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGenConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGenConfigRequest) ProtoMessage() {}

func (x *UserGenConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGenConfigRequest.ProtoReflect.Descriptor instead.
func (*UserGenConfigRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserGenConfigRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserResponse_User   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetUsers() []*UserResponse_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserGenConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientConfig  string                 `protobuf:"bytes,1,opt,name=client_config,json=clientConfig,proto3" json:"client_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGenConfigResponse) Reset() {
	*x = UserGenConfigResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGenConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGenConfigResponse) ProtoMessage() {}

func (x *UserGenConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGenConfigResponse.ProtoReflect.Descriptor instead.
func (*UserGenConfigResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserGenConfigResponse) GetClientConfig() string {
	if x != nil {
		return x.ClientConfig
	}
	return ""
}

type UserResponse_User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Username           string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ServerSerialNumber string                 `protobuf:"bytes,2,opt,name=server_serial_number,json=serverSerialNumber,proto3" json:"server_serial_number,omitempty"`
	Cert               string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IpNet              string                 `protobuf:"bytes,5,opt,name=ip_net,json=ipNet,proto3" json:"ip_net,omitempty"`
	NoGw               bool                   `protobuf:"varint,6,opt,name=no_gw,json=noGw,proto3" json:"no_gw,omitempty"`
	HostId             uint32                 `protobuf:"varint,7,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	IsAdmin            bool                   `protobuf:"varint,8,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsConnected        bool                   `protobuf:"varint,9,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	ConnectedSince     string                 `protobuf:"bytes,10,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"`
	BytesSent          uint64                 `protobuf:"varint,11,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived      uint64                 `protobuf:"varint,12,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Description        string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Tx                 float32                `protobuf:"fixed32,15,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx                 float32                `protobuf:"fixed32,16,opt,name=rx,proto3" json:"rx,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserResponse_User) Reset() {
	*x = UserResponse_User{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse_User) ProtoMessage() {}

func (x *UserResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse_User.ProtoReflect.Descriptor instead.
func (*UserResponse_User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UserResponse_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse_User) GetServerSerialNumber() string {
	if x != nil {
		return x.ServerSerialNumber
	}
	return ""
}

func (x *UserResponse_User) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *UserResponse_User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse_User) GetIpNet() string {
	if x != nil {
		return x.IpNet
	}
	return ""
}

func (x *UserResponse_User) GetNoGw() bool {
	if x != nil {
		return x.NoGw
	}
	return false
}

func (x *UserResponse_User) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *UserResponse_User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UserResponse_User) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *UserResponse_User) GetConnectedSince() string {
	if x != nil {
		return x.ConnectedSince
	}
	return ""
}

func (x *UserResponse_User) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *UserResponse_User) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *UserResponse_User) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *UserResponse_User) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserResponse_User) GetTx() float32 {
	if x != nil {
		return x.Tx
	}
	return 0
}

func (x *UserResponse_User) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fUserListRequest\"\xb6\x01\n" +
	"\x11UserCreateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x13\n" +
	"\x05no_gw\x18\x03 \x01(\bR\x04noGw\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\rR\x06hostId\x12\x19\n" +
	"\bis_admin\x18\x05 \x01(\bR\aisAdmin\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"\xd7\x03\n" +
	"\x11UserUpdateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x124\n" +
	"\x06gwpref\x18\x03 \x01(\x0e2\x1c.pb.UserUpdateRequest.GWPrefR\x06gwpref\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\rR\x06hostId\x12A\n" +
	"\vstatic_pref\x18\x05 \x01(\x0e2 .pb.UserUpdateRequest.StaticPrefR\n" +
	"staticPref\x12>\n" +
	"\n" +
	"admin_pref\x18\x06 \x01(\x0e2\x1f.pb.UserUpdateRequest.AdminPrefR\tadminPref\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"&\n" +
	"\x06GWPref\x12\n" +
	"\n" +
	"\x06NOPREF\x10\x00\x12\b\n" +
	"\x04NOGW\x10\x01\x12\x06\n" +
	"\x02GW\x10\x02\"8\n" +
	"\n" +
	"StaticPref\x12\x10\n" +
	"\fNOPREFSTATIC\x10\x00\x12\f\n" +
	"\bNOSTATIC\x10\x01\x12\n" +
	"\n" +
	"\x06STATIC\x10\x02\"4\n" +
	"\tAdminPref\x12\x0f\n" +
	"\vNOPREFADMIN\x10\x00\x12\v\n" +
	"\aNOADMIN\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\"/\n" +
	"\x11UserDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\".\n" +
	"\x10UserRenewRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"2\n" +
	"\x14UserGenConfigRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x98\x04\n" +
	"\fUserResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.pb.UserResponse.UserR\x05users\x1a\xda\x03\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x120\n" +
	"\x14server_serial_number\x18\x02 \x01(\tR\x12serverSerialNumber\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x15\n" +
	"\x06ip_net\x18\x05 \x01(\tR\x05ipNet\x12\x13\n" +
	"\x05no_gw\x18\x06 \x01(\bR\x04noGw\x12\x17\n" +
	"\ahost_id\x18\a \x01(\rR\x06hostId\x12\x19\n" +
	"\bis_admin\x18\b \x01(\bR\aisAdmin\x12!\n" +
	"\fis_connected\x18\t \x01(\bR\visConnected\x12'\n" +
	"\x0fconnected_since\x18\n" +
	" \x01(\tR\x0econnectedSince\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\v \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\f \x01(\x04R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"expires_at\x18\r \x01(\tR\texpiresAt\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12\x0e\n" +
	"\x02tx\x18\x0f \x01(\x02R\x02tx\x12\x0e\n" +
	"\x02rx\x18\x10 \x01(\x02R\x02rx\"<\n" +
	"\x15UserGenConfigResponse\x12#\n" +
	"\rclient_config\x18\x01 \x01(\tR\fclientConfig2\x85\x04\n" +
	"\vUserService\x12H\n" +
	"\x04List\x12\x13.pb.UserListRequest\x1a\x10.pb.UserResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/user/list\x12Q\n" +
	"\x06Create\x12\x15.pb.UserCreateRequest\x1a\x10.pb.UserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/user/create\x12Q\n" +
	"\x06Update\x12\x15.pb.UserUpdateRequest\x1a\x10.pb.UserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/user/update\x12Q\n" +
	"\x06Delete\x12\x15.pb.UserDeleteRequest\x1a\x10.pb.UserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/user/delete\x12N\n" +
	"\x05Renew\x12\x14.pb.UserRenewRequest\x1a\x10.pb.UserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/user/renew\x12c\n" +
	"\tGenConfig\x12\x18.pb.UserGenConfigRequest\x1a\x19.pb.UserGenConfigResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/user/genconfigB\"Z github.com/GoldenRUS/ovpm/api/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_proto_goTypes = []any{
	(UserUpdateRequest_GWPref)(0),     // 0: pb.UserUpdateRequest.GWPref
	(UserUpdateRequest_StaticPref)(0), // 1: pb.UserUpdateRequest.StaticPref
	(UserUpdateRequest_AdminPref)(0),  // 2: pb.UserUpdateRequest.AdminPref
	(*UserListRequest)(nil),           // 3: pb.UserListRequest
	(*UserCreateRequest)(nil),         // 4: pb.UserCreateRequest
	(*UserUpdateRequest)(nil),         // 5: pb.UserUpdateRequest
	(*UserDeleteRequest)(nil),         // 6: pb.UserDeleteRequest
	(*UserRenewRequest)(nil),          // 7: pb.UserRenewRequest
	(*UserGenConfigRequest)(nil),      // 8: pb.UserGenConfigRequest
	(*UserResponse)(nil),              // 9: pb.UserResponse
	(*UserGenConfigResponse)(nil),     // 10: pb.UserGenConfigResponse
	(*UserResponse_User)(nil),         // 11: pb.UserResponse.User
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: pb.UserUpdateRequest.gwpref:type_name -> pb.UserUpdateRequest.GWPref
	1,  // 1: pb.UserUpdateRequest.static_pref:type_name -> pb.UserUpdateRequest.StaticPref
	2,  // 2: pb.UserUpdateRequest.admin_pref:type_name -> pb.UserUpdateRequest.AdminPref
	11, // 3: pb.UserResponse.users:type_name -> pb.UserResponse.User
	3,  // 4: pb.UserService.List:input_type -> pb.UserListRequest
	4,  // 5: pb.UserService.Create:input_type -> pb.UserCreateRequest
	5,  // 6: pb.UserService.Update:input_type -> pb.UserUpdateRequest
	6,  // 7: pb.UserService.Delete:input_type -> pb.UserDeleteRequest
	7,  // 8: pb.UserService.Renew:input_type -> pb.UserRenewRequest
	8,  // 9: pb.UserService.GenConfig:input_type -> pb.UserGenConfigRequest
	9,  // 10: pb.UserService.List:output_type -> pb.UserResponse
	9,  // 11: pb.UserService.Create:output_type -> pb.UserResponse
	9,  // 12: pb.UserService.Update:output_type -> pb.UserResponse
	9,  // 13: pb.UserService.Delete:output_type -> pb.UserResponse
	9,  // 14: pb.UserService.Renew:output_type -> pb.UserResponse
	10, // 15: pb.UserService.GenConfig:output_type -> pb.UserGenConfigResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
