// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: vpn.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VPNProto int32

const (
	VPNProto_NOPREF VPNProto = 0
	VPNProto_UDP    VPNProto = 1
	VPNProto_TCP    VPNProto = 2
)

// Enum value maps for VPNProto.
var (
	VPNProto_name = map[int32]string{
		0: "NOPREF",
		1: "UDP",
		2: "TCP",
	}
	VPNProto_value = map[string]int32{
		"NOPREF": 0,
		"UDP":    1,
		"TCP":    2,
	}
)

func (x VPNProto) Enum() *VPNProto {
	p := new(VPNProto)
	*p = x
	return p
}

func (x VPNProto) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VPNProto) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_proto_enumTypes[0].Descriptor()
}

func (VPNProto) Type() protoreflect.EnumType {
	return &file_vpn_proto_enumTypes[0]
}

func (x VPNProto) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VPNProto.Descriptor instead.
func (VPNProto) EnumDescriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{0}
}

type VPNLZOPref int32

const (
	VPNLZOPref_USE_LZO_NOPREF  VPNLZOPref = 0
	VPNLZOPref_USE_LZO_ENABLE  VPNLZOPref = 1
	VPNLZOPref_USE_LZO_DISABLE VPNLZOPref = 3
)

// Enum value maps for VPNLZOPref.
var (
	VPNLZOPref_name = map[int32]string{
		0: "USE_LZO_NOPREF",
		1: "USE_LZO_ENABLE",
		3: "USE_LZO_DISABLE",
	}
	VPNLZOPref_value = map[string]int32{
		"USE_LZO_NOPREF":  0,
		"USE_LZO_ENABLE":  1,
		"USE_LZO_DISABLE": 3,
	}
)

func (x VPNLZOPref) Enum() *VPNLZOPref {
	p := new(VPNLZOPref)
	*p = x
	return p
}

func (x VPNLZOPref) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VPNLZOPref) Descriptor() protoreflect.EnumDescriptor {
	return file_vpn_proto_enumTypes[1].Descriptor()
}

func (VPNLZOPref) Type() protoreflect.EnumType {
	return &file_vpn_proto_enumTypes[1]
}

func (x VPNLZOPref) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VPNLZOPref.Descriptor instead.
func (VPNLZOPref) EnumDescriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{1}
}

type VPNStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNStatusRequest) Reset() {
	*x = VPNStatusRequest{}
	mi := &file_vpn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNStatusRequest) ProtoMessage() {}

func (x *VPNStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNStatusRequest.ProtoReflect.Descriptor instead.
func (*VPNStatusRequest) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{0}
}

type VPNInitRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port             string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ProtoPref        VPNProto               `protobuf:"varint,3,opt,name=proto_pref,json=protoPref,proto3,enum=pb.VPNProto" json:"proto_pref,omitempty"`
	IpBlock          string                 `protobuf:"bytes,4,opt,name=ip_block,json=ipBlock,proto3" json:"ip_block,omitempty"`
	Dns              string                 `protobuf:"bytes,5,opt,name=dns,proto3" json:"dns,omitempty"`
	KeepalivePeriod  string                 `protobuf:"bytes,6,opt,name=keepalive_period,json=keepalivePeriod,proto3" json:"keepalive_period,omitempty"`
	KeepaliveTimeout string                 `protobuf:"bytes,7,opt,name=keepalive_timeout,json=keepaliveTimeout,proto3" json:"keepalive_timeout,omitempty"`
	UseLzo           bool                   `protobuf:"varint,8,opt,name=use_lzo,json=useLzo,proto3" json:"use_lzo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VPNInitRequest) Reset() {
	*x = VPNInitRequest{}
	mi := &file_vpn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNInitRequest) ProtoMessage() {}

func (x *VPNInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNInitRequest.ProtoReflect.Descriptor instead.
func (*VPNInitRequest) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{1}
}

func (x *VPNInitRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *VPNInitRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *VPNInitRequest) GetProtoPref() VPNProto {
	if x != nil {
		return x.ProtoPref
	}
	return VPNProto_NOPREF
}

func (x *VPNInitRequest) GetIpBlock() string {
	if x != nil {
		return x.IpBlock
	}
	return ""
}

func (x *VPNInitRequest) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *VPNInitRequest) GetKeepalivePeriod() string {
	if x != nil {
		return x.KeepalivePeriod
	}
	return ""
}

func (x *VPNInitRequest) GetKeepaliveTimeout() string {
	if x != nil {
		return x.KeepaliveTimeout
	}
	return ""
}

func (x *VPNInitRequest) GetUseLzo() bool {
	if x != nil {
		return x.UseLzo
	}
	return false
}

type VPNUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpBlock       string                 `protobuf:"bytes,1,opt,name=ip_block,json=ipBlock,proto3" json:"ip_block,omitempty"`
	Dns           string                 `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	LzoPref       VPNLZOPref             `protobuf:"varint,3,opt,name=lzo_pref,json=lzoPref,proto3,enum=pb.VPNLZOPref" json:"lzo_pref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNUpdateRequest) Reset() {
	*x = VPNUpdateRequest{}
	mi := &file_vpn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNUpdateRequest) ProtoMessage() {}

func (x *VPNUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNUpdateRequest.ProtoReflect.Descriptor instead.
func (*VPNUpdateRequest) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{2}
}

func (x *VPNUpdateRequest) GetIpBlock() string {
	if x != nil {
		return x.IpBlock
	}
	return ""
}

func (x *VPNUpdateRequest) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *VPNUpdateRequest) GetLzoPref() VPNLZOPref {
	if x != nil {
		return x.LzoPref
	}
	return VPNLZOPref_USE_LZO_NOPREF
}

type VPNRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNRestartRequest) Reset() {
	*x = VPNRestartRequest{}
	mi := &file_vpn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNRestartRequest) ProtoMessage() {}

func (x *VPNRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNRestartRequest.ProtoReflect.Descriptor instead.
func (*VPNRestartRequest) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{3}
}

type VPNStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Cert          string                 `protobuf:"bytes,5,opt,name=cert,proto3" json:"cert,omitempty"`
	CaCert        string                 `protobuf:"bytes,6,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	Net           string                 `protobuf:"bytes,7,opt,name=net,proto3" json:"net,omitempty"`
	Mask          string                 `protobuf:"bytes,8,opt,name=mask,proto3" json:"mask,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Proto         string                 `protobuf:"bytes,10,opt,name=proto,proto3" json:"proto,omitempty"`
	Dns           string                 `protobuf:"bytes,11,opt,name=dns,proto3" json:"dns,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CaExpiresAt   string                 `protobuf:"bytes,13,opt,name=ca_expires_at,json=caExpiresAt,proto3" json:"ca_expires_at,omitempty"`
	UseLzo        bool                   `protobuf:"varint,14,opt,name=use_lzo,json=useLzo,proto3" json:"use_lzo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNStatusResponse) Reset() {
	*x = VPNStatusResponse{}
	mi := &file_vpn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNStatusResponse) ProtoMessage() {}

func (x *VPNStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNStatusResponse.ProtoReflect.Descriptor instead.
func (*VPNStatusResponse) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{4}
}

func (x *VPNStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VPNStatusResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *VPNStatusResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *VPNStatusResponse) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *VPNStatusResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *VPNStatusResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *VPNStatusResponse) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *VPNStatusResponse) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *VPNStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VPNStatusResponse) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *VPNStatusResponse) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *VPNStatusResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *VPNStatusResponse) GetCaExpiresAt() string {
	if x != nil {
		return x.CaExpiresAt
	}
	return ""
}

func (x *VPNStatusResponse) GetUseLzo() bool {
	if x != nil {
		return x.UseLzo
	}
	return false
}

type VPNInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNInitResponse) Reset() {
	*x = VPNInitResponse{}
	mi := &file_vpn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNInitResponse) ProtoMessage() {}

func (x *VPNInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNInitResponse.ProtoReflect.Descriptor instead.
func (*VPNInitResponse) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{5}
}

type VPNUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNUpdateResponse) Reset() {
	*x = VPNUpdateResponse{}
	mi := &file_vpn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNUpdateResponse) ProtoMessage() {}

func (x *VPNUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNUpdateResponse.ProtoReflect.Descriptor instead.
func (*VPNUpdateResponse) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{6}
}

type VPNRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPNRestartResponse) Reset() {
	*x = VPNRestartResponse{}
	mi := &file_vpn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPNRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPNRestartResponse) ProtoMessage() {}

func (x *VPNRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPNRestartResponse.ProtoReflect.Descriptor instead.
func (*VPNRestartResponse) Descriptor() ([]byte, []int) {
	return file_vpn_proto_rawDescGZIP(), []int{7}
}

var File_vpn_proto protoreflect.FileDescriptor

const file_vpn_proto_rawDesc = "" +
	"\n" +
	"\tvpn.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10VPNStatusRequest\"\x8b\x02\n" +
	"\x0eVPNInitRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12+\n" +
	"\n" +
	"proto_pref\x18\x03 \x01(\x0e2\f.pb.VPNProtoR\tprotoPref\x12\x19\n" +
	"\bip_block\x18\x04 \x01(\tR\aipBlock\x12\x10\n" +
	"\x03dns\x18\x05 \x01(\tR\x03dns\x12)\n" +
	"\x10keepalive_period\x18\x06 \x01(\tR\x0fkeepalivePeriod\x12+\n" +
	"\x11keepalive_timeout\x18\a \x01(\tR\x10keepaliveTimeout\x12\x17\n" +
	"\ause_lzo\x18\b \x01(\bR\x06useLzo\"j\n" +
	"\x10VPNUpdateRequest\x12\x19\n" +
	"\bip_block\x18\x01 \x01(\tR\aipBlock\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\tR\x03dns\x12)\n" +
	"\blzo_pref\x18\x03 \x01(\x0e2\x0e.pb.VPNLZOPrefR\alzoPref\"\x13\n" +
	"\x11VPNRestartRequest\"\xf2\x02\n" +
	"\x11VPNStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12\x12\n" +
	"\x04cert\x18\x05 \x01(\tR\x04cert\x12\x17\n" +
	"\aca_cert\x18\x06 \x01(\tR\x06caCert\x12\x10\n" +
	"\x03net\x18\a \x01(\tR\x03net\x12\x12\n" +
	"\x04mask\x18\b \x01(\tR\x04mask\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05proto\x18\n" +
	" \x01(\tR\x05proto\x12\x10\n" +
	"\x03dns\x18\v \x01(\tR\x03dns\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAt\x12\"\n" +
	"\rca_expires_at\x18\r \x01(\tR\vcaExpiresAt\x12\x17\n" +
	"\ause_lzo\x18\x0e \x01(\bR\x06useLzo\"\x11\n" +
	"\x0fVPNInitResponse\"\x13\n" +
	"\x11VPNUpdateResponse\"\x14\n" +
	"\x12VPNRestartResponse*(\n" +
	"\bVPNProto\x12\n" +
	"\n" +
	"\x06NOPREF\x10\x00\x12\a\n" +
	"\x03UDP\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02*I\n" +
	"\n" +
	"VPNLZOPref\x12\x12\n" +
	"\x0eUSE_LZO_NOPREF\x10\x00\x12\x12\n" +
	"\x0eUSE_LZO_ENABLE\x10\x01\x12\x13\n" +
	"\x0fUSE_LZO_DISABLE\x10\x032\xda\x02\n" +
	"\n" +
	"VPNService\x12Q\n" +
	"\x06Status\x12\x14.pb.VPNStatusRequest\x1a\x15.pb.VPNStatusResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/vpn/status\x12L\n" +
	"\x04Init\x12\x12.pb.VPNInitRequest\x1a\x13.pb.VPNInitResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/vpn/init\x12T\n" +
	"\x06Update\x12\x14.pb.VPNUpdateRequest\x1a\x15.pb.VPNUpdateResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/vpn/update\x12U\n" +
	"\aRestart\x12\x15.pb.VPNRestartRequest\x1a\x16.pb.VPNRestartResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/vpn/restartB\x1cZ\x1agithub.com/cad/ovpm/api/pbb\x06proto3"

var (
	file_vpn_proto_rawDescOnce sync.Once
	file_vpn_proto_rawDescData []byte
)

func file_vpn_proto_rawDescGZIP() []byte {
	file_vpn_proto_rawDescOnce.Do(func() {
		file_vpn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpn_proto_rawDesc), len(file_vpn_proto_rawDesc)))
	})
	return file_vpn_proto_rawDescData
}

var file_vpn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vpn_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_vpn_proto_goTypes = []any{
	(VPNProto)(0),              // 0: pb.VPNProto
	(VPNLZOPref)(0),            // 1: pb.VPNLZOPref
	(*VPNStatusRequest)(nil),   // 2: pb.VPNStatusRequest
	(*VPNInitRequest)(nil),     // 3: pb.VPNInitRequest
	(*VPNUpdateRequest)(nil),   // 4: pb.VPNUpdateRequest
	(*VPNRestartRequest)(nil),  // 5: pb.VPNRestartRequest
	(*VPNStatusResponse)(nil),  // 6: pb.VPNStatusResponse
	(*VPNInitResponse)(nil),    // 7: pb.VPNInitResponse
	(*VPNUpdateResponse)(nil),  // 8: pb.VPNUpdateResponse
	(*VPNRestartResponse)(nil), // 9: pb.VPNRestartResponse
}
var file_vpn_proto_depIdxs = []int32{
	0, // 0: pb.VPNInitRequest.proto_pref:type_name -> pb.VPNProto
	1, // 1: pb.VPNUpdateRequest.lzo_pref:type_name -> pb.VPNLZOPref
	2, // 2: pb.VPNService.Status:input_type -> pb.VPNStatusRequest
	3, // 3: pb.VPNService.Init:input_type -> pb.VPNInitRequest
	4, // 4: pb.VPNService.Update:input_type -> pb.VPNUpdateRequest
	5, // 5: pb.VPNService.Restart:input_type -> pb.VPNRestartRequest
	6, // 6: pb.VPNService.Status:output_type -> pb.VPNStatusResponse
	7, // 7: pb.VPNService.Init:output_type -> pb.VPNInitResponse
	8, // 8: pb.VPNService.Update:output_type -> pb.VPNUpdateResponse
	9, // 9: pb.VPNService.Restart:output_type -> pb.VPNRestartResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vpn_proto_init() }
func file_vpn_proto_init() {
	if File_vpn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpn_proto_rawDesc), len(file_vpn_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpn_proto_goTypes,
		DependencyIndexes: file_vpn_proto_depIdxs,
		EnumInfos:         file_vpn_proto_enumTypes,
		MessageInfos:      file_vpn_proto_msgTypes,
	}.Build()
	File_vpn_proto = out.File
	file_vpn_proto_goTypes = nil
	file_vpn_proto_depIdxs = nil
}
